version: '2'
services:
  masimosjhipster-app:
    image: masimosjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://masimosjhipster-mysql:3306/masimosjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://masimosjhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://masimosjhipster-elasticsearch:9200
    ports:
      - 9001:9001
  masimosjhipster-mysql:
    extends:
      file: mysql.yml
      service: masimosjhipster-mysql
  masimosjhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: masimosjhipster-elasticsearch
